name: CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Format check
              run: cargo fmt --all -- --check

            - name: Lint
              run: cargo clippy --all-targets -- -D warnings

            - name: Test
              run: cargo test --workspace

            - name: Build
              run: cargo build --workspace --release
