# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Demo CI

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'demo/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'demo/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Clean frontend artifacts
        run: |
          rm -rf demo/node_modules
          rm -rf demo/dist

      - name: Set up Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: "22"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: "10.8.0"

      - name: Install dependencies
        run: |
          cd demo
          pnpm install --force --no-cache

      - name: Build frontend
        run: |
          cd demo
          pnpm run build

      - name: Run lint
        run: |
          cd demo
          rm cypress.config.d.ts
          rm vitest.config.d.ts
          pnpm run lint --no-cache
